project: "My-Go-Pipeline"
max_parallel: 2
stages:
  - name: "Linting"
    command: "go"
    args: ["vet", "./..."]
    parallel: true
  - name: "Security Check"
    command: "go"
    args: ["test", "-race", "-v", "./..."]
    parallel: true
    env:
      GOFLAGS: "-mod=mod"
  - name: "Build Binary"
    command: "go"
    args: ["build", "-o", "gopipe", "."]