project: "My-Go-Pipeline"
stages:
  - name: "Linting"
    command: "go"
    args: ["vet", "./..."]
    parallel: true
  - name: "Security Check"
    command: "go"
    args: ["test", "-race", "-v", "./..."]
    parallel: true
  - name: "Build Binary"
    command: "go"
    args: ["build", "-o", "gopipe", "."]
    parallel: false